spring:
  # 시큐리티 키클록
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://polar-keycloak/realms/PolarBookshop
  data:
    redis:
      host: polar-redis